package com.Movie.IMDB.rating;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity   //the inheritance of classes are managed by this spring boot annotation
public class Movie {
    @Id      //This annotation sets the id (as it is above id) as the primary key
    @GeneratedValue(strategy = GenerationType.AUTO) //this auto generates the primary key id
    private int id;// integers are auto generated id
    private String movieName; //string cant be autogenerated id
    private String movieDescription;

    @Override
    public String toString() {  //integers and keys are converted to string
        return "Movie{" +       //for JSON notation ("keys":"values")
                "id=" + id +
                ", movieName='" + movieName + '\'' +
                ", movieDescription='" + movieDescription + '\'' +
                '}';
    }

    public Movie()
    {
        this.id=0;
        this.movieName="";
        this.movieDescription="";
    }

    //URI contains both URL and URN to identify the name and location or both of a resource;
    // URL is a subset of URI and only identifies the location of the resource
    public Movie(int id, String movieName, String movieDescription) {
        // This keyword refers to the current object(local variable) of java  class
        this.id = id;
        this.movieName = movieName;
        this.movieDescription = movieDescription;
    }

    // Getters are for getting the details and Setters are for assigning the details to the variables.
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getMovieName() {
        return movieName;
    }

    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }

    public String getMovieDescription() {
        return movieDescription;
    }

    public void setMovieDescription(String movieDescription) {
        this.movieDescription = movieDescription;
    }


}

